import { Request, Response } from 'express';

export const estimateValuation = async (req: Request, res: Response) => {
  try {
    const { city, areaSize, areaUnit, type, bedrooms, bathrooms } = req.body;

    if (!city || !areaSize || !type) {
      return res.status(400).json({ error: 'City, area size, and property type are required for valuation estimation.' });
    }

    const size = parseFloat(areaSize);
    let basePricePerMarla = 1200000; // default base price per marla (approx 12 Lakhs PKR)

    const normalizedCity = city.toLowerCase().trim();
    if (normalizedCity.includes('islamabad')) {
      basePricePerMarla = 2500000; // 25 Lakhs
    } else if (normalizedCity.includes('lahore')) {
      basePricePerMarla = 2000000; // 20 Lakhs
    } else if (normalizedCity.includes('karachi')) {
      basePricePerMarla = 2200000; // 22 Lakhs
    } else if (normalizedCity.includes('rawalpindi')) {
      basePricePerMarla = 1400000; // 14 Lakhs
    }

    // Adjust for Unit
    let totalMarlas = size;
    if (areaUnit === 'KANAL') {
      totalMarlas = size * 20;
    } else if (areaUnit === 'SQFT') {
      totalMarlas = size / 272.25;
    } else if (areaUnit === 'SQYD') {
      totalMarlas = size / 30.25;
    }

    let estimatedValue = basePricePerMarla * totalMarlas;

    // Adjust for Bedrooms / Bathrooms
    const rooms = (parseInt(bedrooms) || 0) + (parseInt(bathrooms) || 0);
    estimatedValue += rooms * 500000; // add 5 Lakhs per room

    // Adjust for Property Type
    if (type === 'APARTMENT') {
      estimatedValue *= 0.8; // Apartments are generally cheaper than houses per marla
    } else if (type === 'COMMERCIAL') {
      estimatedValue *= 1.8; // Commercial is much more expensive
    }

    const minEstimated = Math.round(estimatedValue * 0.9);
    const maxEstimated = Math.round(estimatedValue * 1.1);

    res.status(200).json({
      estimatedPrice: Math.round(estimatedValue),
      priceRange: {
        min: minEstimated,
        max: maxEstimated,
      },
      confidenceScore: 0.89,
      note: 'This valuation estimate is generated by PropertyHub AI engine based on current market listings.',
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message || 'Internal server error' });
  }
};

export const generateDescription = async (req: Request, res: Response) => {
  try {
    const { title, type, city, area, bedrooms, bathrooms, amenities } = req.body;

    if (!type || !city || !area) {
      return res.status(400).json({ error: 'Property type, city, and area are required.' });
    }

    const amenitiesStr = amenities && Array.isArray(amenities) ? amenities.join(', ') : 'standard amenities';
    const bedsText = bedrooms ? `${bedrooms} Bedrooms` : '';
    const bathsText = bathrooms ? `${bathrooms} Bathrooms` : '';
    const specs = [bedsText, bathsText].filter(Boolean).join(' and ');

    const descriptionEn = `Explore this beautiful, newly constructed ${type.toLowerCase()} located in the prime sector of ${area}, ${city}. Designed with modern infrastructure and spacious layouts, it offers ${specs}. Enjoy access to top-tier facilities including ${amenitiesStr}. Perfect for families looking for comfort and luxury in a secure gated community. Near schools, hospitals, and major markets. Contact us today for a booking!`;

    const descriptionUr = `مقام: ${area}، ${city} میں واقع یہ شاندار اور جدید طرز پر تعمیر شدہ ${type === 'HOUSE' ? 'مکان' : 'فلیٹ'} فروخت کے لیے تیار ہے۔ جس میں کشادہ اور خوبصورت ${bedrooms || 0} بیڈ رومز اور ${bathrooms || 0} باتھ رومز شامل ہیں۔ پانی، بجلی، اور گیس سمیت ${amenitiesStr} کی تمام بنیادی سہولیات موجود ہیں۔ اسکولوں، ہسپتالوں، اور مارکیٹ کے قریب ترین پرسکون اور محفوظ رہائش گاہ۔ ابھی رابطہ کریں!`;

    res.status(200).json({
      titleEn: `${bedrooms ? bedrooms + ' Bed ' : ''}${type} for Sale in ${area}, ${city}`,
      titleUr: `${area}، ${city} میں ${bedrooms || 0} بیڈ روم والا ${type === 'HOUSE' ? 'مکان' : 'فلیٹ'} برائے فروخت`,
      descriptionEn,
      descriptionUr,
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message || 'Internal server error' });
  }
};

export const fraudCheck = async (req: Request, res: Response) => {
  try {
    const { title, description, price, city, areaSize } = req.body;

    let fraudScore = 0.05; // Base safe score
    const flags: string[] = [];

    const parsedPrice = parseFloat(price);
    const size = parseFloat(areaSize);

    if (parsedPrice && size) {
      // Extremely low price check (e.g. less than 10,000 PKR per marla)
      const pricePerMarla = parsedPrice / size;
      if (pricePerMarla < 50000) {
        fraudScore += 0.45;
        flags.push('Extremely low price listed relative to area size.');
      }
    }

    if (description && description.length < 20) {
      fraudScore += 0.2;
      flags.push('Vague property description.');
    }

    const suspiciousKeywords = ['guaranteed return', 'double money', 'wire transfer only', 'no cnic', 'no documents required'];
    const lowerDesc = (description || '').toLowerCase();
    const lowerTitle = (title || '').toLowerCase();

    suspiciousKeywords.forEach((word) => {
      if (lowerDesc.includes(word) || lowerTitle.includes(word)) {
        fraudScore += 0.25;
        flags.push(`Suspicious terminology detected: "${word}".`);
      }
    });

    res.status(200).json({
      isSuspicious: fraudScore > 0.5,
      fraudScore: Math.min(fraudScore, 1.0),
      flags,
      recommendation: fraudScore > 0.5 ? 'HOLD FOR ADMIN VERIFICATION' : 'AUTO_APPROVE',
    });
  } catch (err: any) {
    res.status(500).json({ error: err.message || 'Internal server error' });
  }
};
